---
- name: Configure GitHub Self Hosted Runner
  hosts: github_runners
  become: true

  vars_files:
    - ../vars/runner.yml

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - docker.io
          - git
          - curl
          - unzip
          - jq
        state: present

    - name: Enable Docker
      service:
        name: docker
        state: started
        enabled: true

    - name: Install AWS CLI
      shell: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o awscliv2.zip
        unzip -o awscliv2.zip
        ./aws/install --update
      args:
        creates: /usr/local/bin/aws

    - name: Install kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
      args:
        creates: /usr/local/bin/kubectl

    - name: Install Helm
      shell: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Install NodeJS
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
        apt-get install -y nodejs
      args:
        creates: /usr/bin/node

    - name: Install .NET SDK 8
      shell: |
        wget https://packages.microsoft.com/config/ubuntu/24.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        dpkg -i packages-microsoft-prod.deb
        apt-get update
        apt-get install -y dotnet-sdk-8.0
      args:
        creates: /usr/bin/dotnet

    - name: Create actions runner directory
      file:
        path: /opt/actions-runner
        state: directory
        owner: ubuntu
        group: ubuntu
        mode: "0755"

    - name: Download GitHub runner
      get_url:
        url: https://github.com/actions/runner/releases/download/v2.325.0/actions-runner-linux-x64-2.325.0.tar.gz
        dest: /tmp/actions-runner.tar.gz

    - name: Extract runner
      unarchive:
        src: /tmp/actions-runner.tar.gz
        dest: /opt/actions-runner
        remote_src: yes

    - name: Fix runner permissions
      file:
        path: /opt/actions-runner
        owner: ubuntu
        group: ubuntu
        recurse: yes

    - name: Get GitHub PAT from AWS Secrets Manager
      shell: |
        aws secretsmanager get-secret-value \
          --secret-id github-runner-pat \
          --query SecretString \
          --output text
      register: github_pat

    - name: Get registration token
      uri:
        url: "https://api.github.com/repos/{{ github_repo }}/actions/runners/registration-token"
        method: POST
        headers:
          Authorization: "token {{ github_pat.stdout }}"
          Accept: "application/vnd.github+json"
        status_code: 201
      register: runner_token

    - name: Configure GitHub Runner
      become: false
      shell: |
        cd /opt/actions-runner

        ./config.sh \
        --url https://github.com/{{ github_repo }} \
        --token {{ runner_token.json.token }} \
        --name $(hostname) \
        --labels {{ runner_labels }} \
        --unattended \
        --replace
      args:
        creates: /opt/actions-runner/.runner

    - name: Install runner service
      shell: |
        cd /opt/actions-runner
        ./svc.sh install

    - name: Start runner service
      shell: |
        cd /opt/actions-runner
        ./svc.sh start