[github_runners]
35.171.129.207
3.83.203.199
100.56.248.148
54.163.170.186

[github_runners:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=~/.ssh/depi-key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'