apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: ecommerce-db-secret
  namespace: default

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: ecommerce-db-secret

  data:
    - secretKey: username
      remoteRef:
        key: ecommerce-db-credentials
        property: username

    - secretKey: password
      remoteRef:
        key: ecommerce-db-credentials
        property: password