name: Terraform Pipeline

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Terraform action"
        required: true
        default: "apply"
        type: choice
        options:
          - apply
          - destroy

permissions:
  id-token: write
  contents: read

jobs:

  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform/environments/dev

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Fix workspace permissions
        run: |
          sudo chown -R $USER:$USER $GITHUB_WORKSPACE || true

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::526015996702:role/github-actions-terraform-role
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan

      - name: Run tfsec
        continue-on-error: true
        run: |
          docker run --rm \
            -v $(pwd):/src \
            --user root \
            aquasec/tfsec /src \
            --format json \
            --out /src/tfsec-report.json

      - name: Upload tfsec report
        uses: actions/upload-artifact@v4
        with:
          name: tfsec-report
          path: terraform/environments/dev/tfsec-report.json

      - name: Run Checkov
        continue-on-error: true
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/tf \
            bridgecrew/checkov \
            -d /tf/terraform \
            -o json > terraform/environments/dev/checkov-report.json

      - name: Upload checkov report
        uses: actions/upload-artifact@v4
        with:
          name: checkov-report
          path: terraform/environments/dev/checkov-report.json

      - name: Run Trivy Config Scan
        continue-on-error: true
        run: |
          docker run --rm \
            -v $(pwd):/work \
            aquasec/trivy:latest config /work \
            --format json \
            --output /work/trivy-report.json

      - name: Upload trivy report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report
          path: terraform/environments/dev/trivy-report.json

      # - name: Upload tfsec report to DefectDojo
      #   continue-on-error: true
      #   run: |
      #     curl -X POST "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
      #       -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
      #       -F "engagement=${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}" \
      #       -F "scan_type=Tfsec Scan" \
      #       -F "file=@tfsec-report.json" \
      #       -F "active=true" \
      #       -F "verified=true"

      # - name: Upload checkov report to DefectDojo
      #   continue-on-error: true
      #   run: |
      #     curl -X POST "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
      #       -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
      #       -F "engagement=${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}" \
      #       -F "scan_type=Checkov Scan" \
      #       -F "file=@checkov-report.json" \
      #       -F "active=true" \
      #       -F "verified=true"

      # - name: Upload trivy report to DefectDojo
      #   continue-on-error: true
      #   run: |
      #     curl -X POST "${{ secrets.DEFECTDOJO_URL }}/api/v2/import-scan/" \
      #       -H "Authorization: Token ${{ secrets.DEFECTDOJO_API_KEY }}" \
      #       -F "engagement=${{ secrets.DEFECTDOJO_ENGAGEMENT_ID }}" \
      #       -F "scan_type=Trivy Config Scan" \
      #       -F "file=@trivy-report.json" \
      #       -F "active=true" \
      #       -F "verified=true"

      - name: Terraform Apply
        if: github.event.inputs.action == 'apply'
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve